import React from "react"
import ReactDOM from "react-dom"
import App from "./App"
import "./assets/css/animate.css"
import "./assets/css/owl.carousel.min.css"
import "./assets/css/owl.theme.default.min.css"
import "./assets/css/magnific-popup.css"
import "./assets/css/flaticon.css"
import "./assets/css/bootstrap.min.css"
import "./assets/css/style.css"
// import "./assets/js/jquery.min.js"
// import "./assets/js/jquery-migrate-3.0.1.min.js"
// import "./assets/js/popper.min.js"
// import "./assets/js/bootstrap.min.js"
// import "./assets/js/jquery.easing.1.3.js"
// import "./assets/js/jquery.waypoints.min.js"
// import "./assets/js/jquery.stellar.min.js"
// import "./assets/js/owl.carousel.min.js"
// import "./assets/js/jquery.magnific-popup.min.js"
// import "./assets/js/jquery.animateNumber.min.js"
// import "./assets/js/scrollax.min.js"
// import "./assets/js/google-map.js"
// import "./assets/js/main.js"

ReactDOM.render(<App/>,document.getElementById("root"))